# https://app.snyk.io/org/folio-org maintained by https://wiki.folio.org/display/SEC
name: Snyk security scan
on: [push, workflow_dispatch]
jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/maven-3-jdk-11@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --org=folio-org --all-projects
          command: monitor
